baseURL = 'https://example.org/'
languageCode = 'ja-JP'
title = "liverHawk's Blog"
theme = 'new-era'

[markup]
    defaultMarkdownHandler = 'goldmark'
    [markup.tableOfContents]
        endLevel = 3
        ordered = false
        startLevel = 2
    [markup.asciidocExt]
        extensions = [ "asciidoctor-diagram" ]
        workingFolderCurrent = true
        [markup.asciidocExt.attributes]
            my-base-url = "https://example.org"
            my-attribute-name = "my-attribute-value"

[security]
    [security.exec]
        allow = [ "^asciidoctor$" ]